"""Permanent, server-side audit trail for the admin panel.

Two independent concerns, both append-only / never auto-pruned:

1. Activity log - a single JSONL file, one line per event (login, upload,
   delete, process, export, ...), used to answer "what did user X do and
   when."
2. Content archive - permanent copies of uploaded files, generated analysis
   output, and exported documents, kept even after the user deletes them
   from their own live workspace (uploads/<user>/, parsed_cache/<user>/)
   so the admin panel can show/download the actual artifact, not just a
   log line.

Every root directory (where files actually live) is passed in by the
caller (app.py, via its existing get_writeable_path() helper) rather than
resolved here - this module stays stateless and path-agnostic, the same
way parser_utils.py never resolves its own paths either.

Trust boundary: `username` arguments are assumed to already be a validated
USERS key (app.py's job to check before calling in here, exactly like the
existing per-user storage helpers in app.py) - never raw, unchecked request
input. `record_id` arguments that originate from a URL (admin browsing a
specific record) ARE treated as untrusted and validated against
_RECORD_ID_RE before being joined into any path, since record ids
generated by this module are the only ones that should ever resolve to a
real file.
"""

import os
import json
import time
import uuid
import shutil
import threading
import re

_RECORD_ID_RE = re.compile(r"^\d+_[0-9a-f]{8}$")

# Guards appends to the activity log. A simple in-process lock is enough -
# this is a single-process app (see app.py's in-memory session store for
# the same reasoning), not a multi-worker deployment.
_activity_lock = threading.Lock()


def new_record_id() -> str:
    return f"{int(time.time())}_{uuid.uuid4().hex[:8]}"


def _validate_record_id(record_id: str) -> None:
    if not _RECORD_ID_RE.match(record_id or ""):
        raise ValueError(f"invalid record id: {record_id!r}")


def _user_dir(root: str, username: str) -> str:
    path = os.path.join(root, username)
    os.makedirs(path, exist_ok=True)
    return path


def _write_meta(user_dir: str, record_id: str, meta: dict) -> None:
    meta_path = os.path.join(user_dir, f"{record_id}.meta.json")
    tmp_path = meta_path + ".tmp"
    with open(tmp_path, "w", encoding="utf-8") as f:
        json.dump(meta, f, ensure_ascii=False, indent=2)
        # fsync before replace, same durability guarantee as app.py's
        # _write_cache_atomic - these records are the permanent audit trail.
        f.flush()
        os.fsync(f.fileno())
    os.replace(tmp_path, meta_path)


def _read_meta(user_dir: str, record_id: str) -> dict | None:
    meta_path = os.path.join(user_dir, f"{record_id}.meta.json")
    if not os.path.exists(meta_path):
        return None
    with open(meta_path, "r", encoding="utf-8") as f:
        return json.load(f)


# ── Activity log ─────────────────────────────────────────────────────

def log_activity(log_path: str, username: str, action: str, **fields) -> None:
    entry = {"ts": time.time(), "username": username, "action": action, **fields}
    line = json.dumps(entry, ensure_ascii=False)
    with _activity_lock:
        with open(log_path, "a", encoding="utf-8") as f:
            f.write(line + "\n")


def read_activity(log_path: str, username: str = None, action: str = None, limit: int = 500) -> list:
    if not os.path.exists(log_path):
        return []
    with _activity_lock:
        with open(log_path, "r", encoding="utf-8") as f:
            lines = f.readlines()
    entries = []
    for line in lines:
        line = line.strip()
        if not line:
            continue
        try:
            entry = json.loads(line)
        except json.JSONDecodeError:
            continue
        if username and entry.get("username") != username:
            continue
        if action and entry.get("action") != action:
            continue
        entries.append(entry)
    entries.sort(key=lambda e: e.get("ts", 0), reverse=True)
    return entries[:limit]


# ── Archive: uploaded files ──────────────────────────────────────────
#
# Copied at upload time (not at delete time) so there's exactly one write
# path to get right, and a crash mid-delete can never lose the archived
# copy. This intentionally costs 2x disk for a live file - acceptable for a
# small local/LAN tool that prioritizes never losing an "actual thing" over
# disk efficiency.

def archive_upload_copy(root: str, username: str, safe_filename: str, src_path: str) -> str:
    record_id = new_record_id()
    user_dir = _user_dir(root, username)
    stored_name = f"{record_id}__{safe_filename}"
    dest_path = os.path.join(user_dir, stored_name)
    shutil.copy2(src_path, dest_path)
    _write_meta(user_dir, record_id, {
        "record_id": record_id,
        "ts": time.time(),
        "filename": safe_filename,
        "stored_name": stored_name,
        "size": os.path.getsize(dest_path),
    })
    return record_id


# ── Archive: analysis runs ───────────────────────────────────────────

def archive_analysis(root: str, username: str, prompt: str, content: str,
                      doc_filenames: list, complete: bool) -> str:
    record_id = new_record_id()
    user_dir = _user_dir(root, username)
    content_path = os.path.join(user_dir, f"{record_id}.md")
    with open(content_path, "w", encoding="utf-8") as f:
        f.write(content)
    _write_meta(user_dir, record_id, {
        "record_id": record_id,
        "ts": time.time(),
        "prompt": prompt,
        "doc_filenames": doc_filenames,
        "complete": complete,
        "content_chars": len(content),
    })
    return record_id


# ── Archive: exported documents ──────────────────────────────────────

def archive_export(root: str, username: str, fmt_key: str, filename: str, file_bytes: bytes,
                    instructions: str, template_filename, ai_generated: bool) -> str:
    record_id = new_record_id()
    user_dir = _user_dir(root, username)
    stored_name = f"{record_id}__{filename}"
    dest_path = os.path.join(user_dir, stored_name)
    with open(dest_path, "wb") as f:
        f.write(file_bytes)
    _write_meta(user_dir, record_id, {
        "record_id": record_id,
        "ts": time.time(),
        "format": fmt_key,
        "filename": filename,
        "stored_name": stored_name,
        "instructions": instructions,
        "template_filename": template_filename,
        "ai_generated": ai_generated,
        "size": len(file_bytes),
    })
    return record_id


# ── Listing / retrieval (used by the admin panel) ────────────────────

def list_archive(root: str, username: str = None) -> list:
    entries = []
    if not os.path.exists(root):
        return entries
    usernames = [username] if username else os.listdir(root)
    for uname in usernames:
        user_dir = os.path.join(root, uname)
        if not os.path.isdir(user_dir):
            continue
        for name in os.listdir(user_dir):
            if name.endswith(".meta.json"):
                try:
                    with open(os.path.join(user_dir, name), "r", encoding="utf-8") as f:
                        meta = json.load(f)
                except (OSError, json.JSONDecodeError):
                    continue
                meta["username"] = uname
                entries.append(meta)
    entries.sort(key=lambda e: e.get("ts", 0), reverse=True)
    return entries


def get_archive_meta(root: str, username: str, record_id: str) -> dict | None:
    _validate_record_id(record_id)
    user_dir = os.path.join(root, username)
    meta = _read_meta(user_dir, record_id)
    if meta is not None:
        meta["username"] = username
    return meta


def get_archive_file_path(root: str, username: str, record_id: str):
    """Resolve an uploads/exports archive record to (abs_path, original
    filename), or None. The path is built from the record's own metadata,
    never from a client-supplied filename directly."""
    meta = get_archive_meta(root, username, record_id)
    if meta is None:
        return None
    stored_name = meta.get("stored_name")
    if not stored_name:
        return None
    path = os.path.join(root, username, stored_name)
    if not os.path.exists(path):
        return None
    return path, meta.get("filename", stored_name)


def get_analysis_content(root: str, username: str, record_id: str) -> str | None:
    _validate_record_id(record_id)
    path = os.path.join(root, username, f"{record_id}.md")
    if not os.path.exists(path):
        return None
    with open(path, "r", encoding="utf-8") as f:
        return f.read()
